-- CreateTable
CREATE TABLE "playerSeasons" (
    "player_id" TEXT NOT NULL,
    "player_name" TEXT NOT NULL,
    "season" INTEGER NOT NULL,
    "games_played" INTEGER NOT NULL,
    "completions_total" DOUBLE PRECISION,
    "attempts_total" DOUBLE PRECISION,
    "passing_yards_total" DOUBLE PRECISION,
    "passing_tds_total" DOUBLE PRECISION,
    "interceptions_total" DOUBLE PRECISION,
    "passing_first_downs_total" DOUBLE PRECISION,
    "carries_total" DOUBLE PRECISION,
    "rushing_yards_total" DOUBLE PRECISION,
    "rushing_tds_total" DOUBLE PRECISION,
    "rushing_fumbles_total" DOUBLE PRECISION,
    "rushing_fumbles_lost_total" DOUBLE PRECISION,
    "rushing_first_downs_total" DOUBLE PRECISION,
    "targets_total" DOUBLE PRECISION,
    "receiving_yards_total" DOUBLE PRECISION,
    "receiving_tds_total" DOUBLE PRECISION,
    "receiving_air_yards_total" DOUBLE PRECISION,
    "receiving_yards_after_catch_total" DOUBLE PRECISION,
    "receiving_first_downs_total" DOUBLE PRECISION,
    "fantasy_points_total" DOUBLE PRECISION,
    "completions_avg" DOUBLE PRECISION,
    "attempts_avg" DOUBLE PRECISION,
    "passing_yards_avg" DOUBLE PRECISION,
    "passing_tds_avg" DOUBLE PRECISION,
    "interceptions_avg" DOUBLE PRECISION,
    "passing_air_yards_avg" DOUBLE PRECISION,
    "passing_yards_after_catch_avg" DOUBLE PRECISION,
    "passing_first_downs_avg" DOUBLE PRECISION,
    "carries_avg" DOUBLE PRECISION,
    "rushing_yards_avg" DOUBLE PRECISION,
    "rushing_tds_avg" DOUBLE PRECISION,
    "rushing_fumbles_avg" DOUBLE PRECISION,
    "rushing_fumbles_lost_avg" DOUBLE PRECISION,
    "rushing_first_downs_avg" DOUBLE PRECISION,
    "rushing_epa_avg" DOUBLE PRECISION,
    "receptions_avg" DOUBLE PRECISION,
    "targets_avg" DOUBLE PRECISION,
    "receiving_yards_avg" DOUBLE PRECISION,
    "receiving_tds_avg" DOUBLE PRECISION,
    "receiving_air_yards_avg" DOUBLE PRECISION,
    "receiving_yards_after_catch_avg" DOUBLE PRECISION,
    "receiving_first_downs_avg" DOUBLE PRECISION,
    "receiving_epa_avg" DOUBLE PRECISION,
    "racr_avg" DOUBLE PRECISION,
    "target_share_avg" DOUBLE PRECISION,
    "air_yards_share_avg" DOUBLE PRECISION,
    "wopr_avg" DOUBLE PRECISION,
    "fantasy_points_avg" DOUBLE PRECISION,
    "fantasy_points_ppr_avg" DOUBLE PRECISION,
    "YPRR" DOUBLE PRECISION,
    "routes" DOUBLE PRECISION,
    "routes_per_game" DOUBLE PRECISION,
    "TPRR" DOUBLE PRECISION,
    "firstDPRR" DOUBLE PRECISION,

    CONSTRAINT "playerSeasons_pkey" PRIMARY KEY ("player_id","season")
);
