-- CreateTable
CREATE TABLE "PlayerStat" (
    "id" TEXT NOT NULL,
    "player_id" TEXT,
    "player_name" TEXT,
    "player_display_name" TEXT,
    "position" TEXT,
    "position_group" TEXT,
    "headshot_url" TEXT,
    "recent_team" TEXT,
    "season" INTEGER,
    "week" INTEGER,
    "season_type" TEXT,
    "opponent_team" TEXT,
    "completions" INTEGER,
    "attempts" INTEGER,
    "passing_yards" DOUBLE PRECISION,
    "passing_tds" INTEGER,
    "interceptions" INTEGER,
    "sacks" INTEGER,
    "sack_yards" DOUBLE PRECISION,
    "sack_fumbles" INTEGER,
    "sack_fumbles_lost" INTEGER,
    "passing_air_yards" DOUBLE PRECISION,
    "passing_yards_after_catch" DOUBLE PRECISION,
    "passing_first_downs" INTEGER,
    "passing_epa" DOUBLE PRECISION,
    "passing_2pt_conversions" INTEGER,
    "pacr" DOUBLE PRECISION,
    "dakota" DOUBLE PRECISION,
    "carries" INTEGER,
    "rushing_yards" DOUBLE PRECISION,
    "rushing_tds" INTEGER,
    "rushing_fumbles" INTEGER,
    "rushing_fumbles_lost" INTEGER,
    "rushing_first_downs" INTEGER,
    "rushing_epa" DOUBLE PRECISION,
    "rushing_2pt_conversions" INTEGER,
    "receptions" INTEGER,
    "targets" INTEGER,
    "receiving_yards" DOUBLE PRECISION,
    "receiving_tds" INTEGER,
    "receiving_fumbles" INTEGER,
    "receiving_fumbles_lost" INTEGER,
    "receiving_air_yards" DOUBLE PRECISION,
    "receiving_yards_after_catch" DOUBLE PRECISION,
    "receiving_first_downs" INTEGER,
    "receiving_epa" DOUBLE PRECISION,
    "receiving_2pt_conversions" INTEGER,
    "racr" DOUBLE PRECISION,
    "target_share" DOUBLE PRECISION,
    "air_yards_share" DOUBLE PRECISION,
    "wopr" DOUBLE PRECISION,
    "special_teams_tds" INTEGER,
    "fantasy_points" DOUBLE PRECISION,
    "fantasy_points_ppr" DOUBLE PRECISION,

    CONSTRAINT "PlayerStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReceivingStat" (
    "id" TEXT NOT NULL,
    "player" TEXT,
    "player_id" TEXT,
    "position" TEXT,
    "team_name" TEXT,
    "player_game_count" INTEGER,
    "avg_depth_of_target" DOUBLE PRECISION,
    "avoided_tackles" INTEGER,
    "caught_percent" DOUBLE PRECISION,
    "contested_catch_rate" DOUBLE PRECISION,
    "contested_receptions" INTEGER,
    "contested_targets" INTEGER,
    "declined_penalties" INTEGER,
    "drop_rate" DOUBLE PRECISION,
    "drops" INTEGER,
    "first_downs" INTEGER,
    "franchise_id" INTEGER,
    "fumbles" INTEGER,
    "grades_hands_drop" DOUBLE PRECISION,
    "grades_hands_fumble" DOUBLE PRECISION,
    "grades_offense" DOUBLE PRECISION,
    "grades_pass_block" DOUBLE PRECISION,
    "grades_pass_route" DOUBLE PRECISION,
    "inline_rate" DOUBLE PRECISION,
    "inline_snaps" INTEGER,
    "interceptions" INTEGER,
    "longest" INTEGER,
    "pass_block_rate" DOUBLE PRECISION,
    "pass_blocks" INTEGER,
    "pass_plays" INTEGER,
    "penalties" INTEGER,
    "receptions" INTEGER,
    "route_rate" DOUBLE PRECISION,
    "routes" INTEGER,
    "slot_rate" DOUBLE PRECISION,
    "slot_snaps" INTEGER,
    "targeted_qb_rating" DOUBLE PRECISION,
    "targets" INTEGER,
    "touchdowns" INTEGER,
    "wide_rate" DOUBLE PRECISION,
    "wide_snaps" INTEGER,
    "yards" INTEGER,
    "yards_after_catch" INTEGER,
    "yards_after_catch_per_reception" DOUBLE PRECISION,
    "yards_per_reception" DOUBLE PRECISION,
    "yprr" DOUBLE PRECISION,

    CONSTRAINT "ReceivingStat_pkey" PRIMARY KEY ("id")
);
